server:
  port: 8082

spring:
  application:
    name: admissions-service
  datasource:
    url: jdbc:mysql://localhost:3306/admissions_service?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9091/realms/collage_management
