server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admin_service?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


keycloak:
  server-url: http://localhost:9091
  realm: collage_management
  client-id: admin-cli
  username: tusharpandao
  password: Sony@9421
